### ISSUE TITLE
Research options for login and session storage

### ISSUE THREAD

**Issue by jhodapp** [Jim-Hodapp-Coaching/refactor-platform-rs#10]
Research options for facilitating users ability to log in to the platform and establish and store a user session.

[LogRocket's 9 Rust-based authentication options](https://blog.logrocket.com/9-rust-authentication-libraries-that-are-ready-for-production/)

Definition of done (answers these questions):

1. Do we rely on backend session storage, browser-based, or hybrid?
2. How persistent do we need client-side storage to be?
3. What kind of browser-side libraries do we need to facilitate client-side session storage?
4. Is there a Rust-based login crate that provides an existing user login API and storage schema?
5. A proposed solution should use a combination of client-side cookie storage and our existing Postgresql DB

**Comment by jhodapp** [comment]
[axum-login](https://docs.rs/axum-login/latest/axum_login/) looks like a promising option when skimming over the project.

User authentication, supports different kinds of data providers (including IDPs), user session, and protected routes.

**Comment by qafui** [comment]
1. Do we rely on backend session storage, browser-based, or hybrid?\
    
- We discussed a hybrid strategy of backend and browser-based session storage. Auth would be backend while non-sensitive context-based data could be stored on the frontend with Javascript’s sessionstorage API. 

[AuthJS for client side auth](https://authjs.dev)
    
2. How persistent do we need client-side storage to be?
    
- Persist until we clear or the page is closed. 
    
3. What kind of browser-side libraries do we need to facilitate client-side session storage? - - Native window.sessionStorage API

4. Is there a Rust-based login crate that provides an existing user login API and storage schema?
    
- Axum-Login provides a high-level user group backend storage abstractions. 
    
5. A proposed solution should use a combination of client-side cookie storage and our existing Postgresql DB
    
- https://github.com/maxcountryman/axum-login/tree/main/examples/oauth2

**Comment by jhodapp** [comment]
Completed for now, may come back and update as we work with axum-login.
